//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MailManagerEntities : DbContext
    {
        public MailManagerEntities()
            : base("name=MailManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Base_Admin> T_Base_Admin { get; set; }
        public DbSet<T_Base_Class> T_Base_Class { get; set; }
        public DbSet<T_Base_Mail> T_Base_Mail { get; set; }
    }
}
