//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Base_Mail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string Pname { get; set; }
        public string Phone { get; set; }
        public string Tip { get; set; }
    }
}
